### ISSUE TITLE
Bug: Mining with Dragon Pickaxe

### ISSUE THREAD

**Issue by Koslas1** [JonneSaloranta/skilling-boost-reminder#9]
Hi, I'm unsure if this is related to issue #1 however when mining with a dragon pickaxe, at a shooting star, I noticed that it's not giving me a reminder to boost, I'm not sure if that would be due to mining shooting stars having a slightly different animation or something? 

I do also see this in the Runelite code
`public static final int MINING_DRAGON_PICKAXE_UPGRADED = 642;`
`public static final int MINING_DRAGON_PICKAXE_OR = 8346;`
`public static final int MINING_DRAGON_PICKAXE_OR_TRAILBLAZER = 8887;`
`public static final int MINING_INFERNAL_PICKAXE = 4482;`
`public static final int MINING_CRYSTAL_PICKAXE = 8347;`
`public static final int MINING_TRAILBLAZER_PICKAXE = 8787; // Same animation as Infernal pickaxe (or)`
`public static final int MINING_TRAILBLAZER_PICKAXE_2 = 8788;`
`public static final int MINING_TRAILBLAZER_PICKAXE_3 = 8789;`
`public final static int MINING_CRASHEDSTAR_DRAGON = 7140;`
`public final static int MINING_CRASHEDSTAR_DRAGON_UPGRADED = 643;`
`public final static int MINING_CRASHEDSTAR_DRAGON_OR = 8349;`
`public final static int MINING_CRASHEDSTAR_DRAGON_OR_TRAILBLAZER = 8888;`
`public final static int MINING_CRASHEDSTAR_INFERNAL = 4483;`
`public final static int MINING_CRASHEDSTAR_3A = 7284;`
`public final static int MINING_CRASHEDSTAR_CRYSTAL = 8350;`
`public static final int MINING_MOTHERLODE_DRAGON = 6758;`
`public static final int MINING_MOTHERLODE_DRAGON_UPGRADED = 335;`
`public static final int MINING_MOTHERLODE_DRAGON_OR = 8344;`
`public static final int MINING_MOTHERLODE_DRAGON_OR_TRAILBLAZER = 8886;`
`public static final int MINING_MOTHERLODE_INFERNAL = 4481;`
`public static final int MINING_MOTHERLODE_3A = 7282;`
`public static final int MINING_MOTHERLODE_CRYSTAL = 8345;`
`public static final int MINING_MOTHERLODE_TRAILBLAZER = 8786; // Same animation as Infernal pickaxe (or)`

So I'm not sure if it's worth adding all of those, but it may be worth adding the animations 7140 and 6758 so your plugin works with crashed stars and motherlode mine? That's if I'm reading the runelite code properly

**Comment by JonneSaloranta** [comment]
Yes, this is related to #1. These animation IDs need to be added and I'll get to it at some point. I'll leave this issue open
